[package]
name = "Rust_RT_One_Weekend"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.4"
simple-stopwatch = "0.1.2"
lazy_static = "1.4.0"
num = "0.4.0"